# Generated by Django 4.2.7 on 2023-12-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_facebook_user_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='family_status',
            field=models.IntegerField(choices=[(1, 'Married'), (2, 'Not married')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='person_gender',
            field=models.IntegerField(choices=[(1, 'MAN'), (2, 'WOMAN')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
