# Generated by Django 4.2.7 on 2023-12-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_age_user_city_user_country_user_family_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
