# Generated by Django 4.2.7 on 2023-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_private_user_info',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
