# Generated by Django 4.2.7 on 2023-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_status_private_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='family_status',
            field=models.CharField(choices=[('married', 'Married'), ('not_married', 'Not married')], max_length=20),
        ),
    ]
