# Generated by Django 4.2.7 on 2023-12-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_family_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='family_status',
            field=models.CharField(choices=[('married', 'Married'), ('not married', 'Not married')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_gender',
            field=models.CharField(choices=[('Му', 'MAN'), ('WOMAN', 'WOMAN')], max_length=20),
        ),
    ]
