# Generated by Django 5.0.1 on 2024-01-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_experience_user_self_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opening_speech',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
