# Generated by Django 4.2.7 on 2023-12-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidlesson',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ссылка на видео'),
        ),
    ]
