# Generated by Django 4.2.7 on 2023-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_lessons', '0002_alter_paidlesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidlesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
