# Generated by Django 4.2.7 on 2023-12-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paid_lessons', '0004_alter_paidlesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidСhapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок раздела')),
                ('description', models.TextField(verbose_name='Описание раздела')),
                ('duration', models.DurationField(verbose_name='Длительность раздела')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='media/paid_lessons_video', verbose_name='Ссылка на видео')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paid_lessons.paidlesson')),
            ],
        ),
    ]
