# Generated by Django 4.2.7 on 2023-12-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_lessons', '0007_alter_paidсhapter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidсhapter',
            name='description',
            field=models.TextField(verbose_name='Описание раздела'),
        ),
    ]
