# Generated by Django 4.2.7 on 2024-01-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paid_lessons', '0008_alter_paidсhapter_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidlesson',
            options={'verbose_name': 'PaidLesson', 'verbose_name_plural': 'PaidLessons'},
        ),
    ]
