# Generated by Django 4.2.7 on 2024-01-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_lessons', '0009_alter_paidlesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidlesson',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
