# Generated by Django 5.0.1 on 2024-01-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paid_lessons', '0011_paidlesson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidlesson',
            name='status',
        ),
    ]
