# Generated by Django 5.0.1 on 2024-01-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_lessons', '0012_remove_paidlesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidlesson',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='Куплен'),
        ),
    ]
