# Generated by Django 4.2.7 on 2023-12-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='time',
            new_name='created_at',
        ),
    ]
