# Generated by Django 4.2.7 on 2023-12-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0005_alter_opinion_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.IntegerField(blank=True, choices=[('', None), (1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')]),
        ),
    ]
