# Generated by Django 4.2.7 on 2024-01-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidcard',
            old_name='paid_lesson',
            new_name='product',
        ),
        migrations.AddField(
            model_name='paidcard',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidcard',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
