# Generated by Django 4.2.7 on 2024-01-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paid_card', '0002_rename_paid_lesson_paidcard_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidcard',
            old_name='product',
            new_name='paid_lesson',
        ),
    ]
