# Generated by Django 5.0.1 on 2024-01-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_card', '0003_rename_product_paidcard_paid_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidcard',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
