# Generated by Django 5.0.1 on 2024-01-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_card',
            new_name='paid_card_history',
        ),
    ]
