# Generated by Django 5.0.1 on 2024-01-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_paid_card_order_paid_card_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid')], default=0),
        ),
    ]
