# Generated by Django 5.0.1 on 2024-01-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        ('paid_lessons', '0011_paidlesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paid_lessons.paidlesson'),
            preserve_default=False,
        ),
    ]
