# Generated by Django 5.0.1 on 2024-01-07 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_paid_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_lesson',
        ),
    ]
