# Generated by Django 4.2.7 on 2023-12-04 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='language',
        ),
        migrations.AddField(
            model_name='basket',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='languages.category'),
            preserve_default=False,
        ),
    ]
